SET SCHEMA FN71840;

--Scalar function for MANAGERS - returns e-mail by their ID
CREATE FUNCTION GET_MANAGER_EMAIL(MNG_ID CHARACTER(6))
RETURNS VARCHAR(30)
RETURN
    SELECT E_MAIL
    FROM MANAGER
    WHERE ID = MNG_ID;

-- Call the function
VALUES FN71840.GET_MANAGER_EMAIL('MNG205');

-- Call the function in query
SELECT NAME AS MNG_NAME, FN71840.GET_MANAGER_EMAIL(ID) AS MNG_EMAIL
FROM MANAGER;


--Table function for RECEPTIONISTS - returns name, salary and bonus by their ID
CREATE FUNCTION RECEPTIONIST_INFO(REC_ID CHARACTER(6))
RETURNS TABLE(R_NAME VARCHAR(50), R_SALARY DOUBLE, R_BONUS DOUBLE)
RETURN
    SELECT NAME, SALARY, BONUS
    FROM RECEPTIONISTS
    WHERE ID = REC_ID;

-- Call the function
SELECT *
FROM TABLE(FN71840.RECEPTIONIST_INFO('REC621')) T;


-- Scalar function for ROOMS - returns the type of the room by its number
CREATE FUNCTION GET_ROOM_TYPE(R_NUM INTEGER)
RETURNS INTEGER
RETURN
    SELECT R_TYPE
    FROM ROOMS
    WHERE R_NUMBER = R_NUM;

-- Call the function
VALUES FN71840.GET_ROOM_TYPE(201);

-- Call the function in query
SELECT FN71840.GET_ROOM_TYPE(R_NUMBER) AS R_NUM, PRICE AS R_PRICE
FROM ROOMS;


-- Table function for REGISTRATIONS - returns accommodation date, leaving date and room type
CREATE FUNCTION REGISTRATION_DETAILS(R_ID INTEGER)
RETURNS TABLE(ADATE DATE, LDATE DATE, RNUM INTEGER)
RETURN
    SELECT A_DATE, L_DATE, R_NUMBER
    FROM REGISTRATIONS
    WHERE ID = R_ID;

--Call the function
SELECT *
FROM TABLE(FN71840.REGISTRATION_DETAILS(1)) R;


--Scalar function for ATTENDANTS - returns name by their ID
CREATE FUNCTION GET_ATT_NAME(ATT_ID CHARACTER(6))
RETURNS VARCHAR(50)
RETURN
    SELECT NAME
    FROM ATTENDANTS
    WHERE ID = ATT_ID;

-- Call the function
VALUES FN71840.GET_ATT_NAME('ATT133');

-- Call the function in query
SELECT FN71840.GET_ATT_NAME(ID) AS ATT_NAME
FROM ATTENDANTS;


--Table function for GUESTS - returns name, age and phone number
CREATE FUNCTION GUEST_DETAILS(G_EGN CHARACTER(10))
RETURNS TABLE(G_NAME VARCHAR(50), G_AGE INT, G_MOBILE CHAR(10))
RETURN
    SELECT G.NAME, G.AGE, G.PHONE_NUMBER
    FROM GUESTS G
    WHERE G.EGN = G_EGN;

-- Call table function
SELECT *
FROM TABLE(FN71840.GUEST_DETAILS('7801235465')) G;