SET SCHEMA FN71840;

--View on MANAGERS, who have been employed before 2017
CREATE VIEW MANAGERS_BEFORE_2017
AS
    SELECT ID, NAME, EMP_DATE FROM MANAGER
    WHERE EMP_DATE < '2017-01-01';

--View on RECEPTIONISTS, who have made reservations on 3rd floor
CREATE VIEW RECEPTIONISTS_REGISTERED_ON_3_FLOOR
AS
    SELECT ID, NAME FROM RECEPTIONISTS
    WHERE ID IN (
    SELECT DISTINCT RECEPTIONIST_ID FROM REGISTRATIONS
    WHERE R_NUMBER > 300 AND R_NUMBER < 400);

--View on REGISTRATIONS, that have been made in January 2019
CREATE VIEW  REGISTRATION_CURR_YEAR
AS
    SELECT R_NUMBER, A_DATE, DAYS
    FROM REGISTRATIONS
    WHERE YEAR(A_DATE) = '2019'
    AND MONTH(A_DATE) = '01';

--View on ROOMS for two guests
CREATE VIEW TWO_GUESTS_ROOMS
AS
    SELECT *
    FROM ROOMS
    WHERE R_TYPE = 2
    AND ATTENDANT_ID = 'ATT333';

--view on ATTENDANTS, based on their phone number and bonus
CREATE VIEW ATTENT_PHONE_BONUS
AS
    SELECT NAME, PHONE_NUM, BONUS
    FROM ATTENDANTS
    WHERE PHONE_NUM LIKE '088%' AND  BONUS  > 200;

--View on male GUESTS between 20 and 40 years
CREATE VIEW GUESTS_AGE_NAME
AS
    SELECT *
    FROM GUESTS
    WHERE AGE BETWEEN 20 AND 40
    AND NAME LIKE '%ov';