-- alter table PROJECT1
CREATE TABLE PROJECT1
( PROJNO CHAR(6) NOT NULL PRIMARY KEY,
  PROJNAME VARCHAR(24) NOT NULL,
  DEPTNO CHAR(3) NOT NULL,
  RESPEMP CHAR(6) NOT NULL,
  PRSTAFF DECIMAL(5, 2),
  PRSTDATE DATE,
  PRENDATE DATE,
  MAJRPROJ CHAR(6)
);

ALTER TABLE PROJECT1
ADD CONSTRAINT PROJECT_FK
    FOREIGN KEY (DEPTNO)
    REFERENCES DEPARTMENT1(DEPTNO);

-- alter table MovieStar
CREATE TABLE MovieStar
(NAME CHAR(30) NOT NULL,
ADDRESS VARCHAR (255),
GENDER CHAR(1),
BIRTHDATE DATE ,
PRIMARY KEY (NAME)
);

ALTER TABLE MovieStar
ADD PHONE CHAR(16);

ALTER TABLE MovieStar
DROP BIRTHDATE;

-- alter table StarsIn
CREATE TABLE StarsIn(
    MOVIETITLE VARCHAR(50),
    MOVIEYEAR INTEGER,
    NAME CHAR(30),
    FOREIGN KEY (MOVIETITLE, MOVIEYEAR)
                    REFERENCES Movie(TITLE, YEAR)
);

ALTER TABLE StarsIn
ADD [CONSTRAINT MovieStar_FK] FOREIGN KEY (STARNAME)
REFERENCES MOVIESTAR(NAME);


-- update table EMPLOYEE1
CREATE TABLE EMPLOYEE1 (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT PK_EMP PRIMARY KEY ,
    NAME VARCHAR(50),
    AGE INT CONSTRAINT CK_AGE CHECK ( AGE > 0 ),
    CODE INT,
    MANAGER_ID INT REFERENCES EMPLOYEE1(ID),
    CHECK ( ID != MANAGER_ID )
);

ALTER TABLE EMPLOYEE1
    ADD MANAGER_ID INT;

DROP TABLE EMPLOYEE1;

ALTER TABLE EMPLOYEE1
ADD CONSTRAINT PK_EMP_ID PRIMARY KEY(ID);

ALTER TABLE EMPLOYEE1
ADD CONSTRAINT FK_EMP_ID FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID);

ALTER TABLE EMPLOYEE1
ALTER COLUMN ID SET GENERATED ALWAYS AS IDENTITY (START WITH 9 INCREMENT BY 1);

-- insert values into table EMPLOYEE1
INSERT INTO EMPLOYEE1(NAME, AGE, CODE)
VALUES ('Pesho', 23, 15),
       ('Pesho', 23, 15),
       ('Pesho', 23, 15),
       ('Pesho', 23, 15),
       ('Pesho', 23, 15),
       ('Pesho', 23, 15),
       ('Pesho', 23, 15);

INSERT INTO EMPLOYEE1(NAME, AGE, CODE)
VALUES('Maria', 16, 37);

-- delete values from EMPLOYEE
DELETE FROM EMPLOYEE1
WHERE NAME = 'Pesho';

-- update table EMPLOYEE1
UPDATE EMPLOYEE1
SET AGE = 37
WHERE ID =  1;


